#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 15, 2018 05:46:20 PM CST  platform: Windows NT
import numpy as num
import math
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Beta_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    Beta_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    Beta_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    matA = num.array([[None]*2, [None]*2])
    matB = num.array([[None]*2, [None]*2])
    vecA = num.array([None, None])
    vecB = num.array([None, None])
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font13 = "-family Algerian -size 15 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font14 = "-family Constantia -size 12 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("594x450+650+150")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")



        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=0.0, relheight=0.991, relwidth=1.0)
        self.TNotebook1.configure(width=594)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Main Menu", compound="left", underline="-1"
                ,)
        self.TNotebook1_t0.configure(background="#d9d9d9")
        self.TNotebook1_t0.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t0.configure(highlightcolor="black")
        self.TNotebook1_t1 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Vector Calculator", compound="left"
                ,underline="-1", )
        self.TNotebook1_t1.configure(background="#d9d9d9")
        self.TNotebook1_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t1.configure(highlightcolor="black")
        self.TNotebook1_t2 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(2, text="Matrix Calculator", compound="none"
                ,underline="-1", )
        self.TNotebook1_t2.configure(background="#d9d9d9")
        self.TNotebook1_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t2.configure(highlightcolor="black")

        self.Frame4 = Frame(self.TNotebook1_t0)
        self.Frame4.place(relx=0.034, rely=0.049, relheight=0.915
                , relwidth=0.941)
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(background="#d9d9d9")
        self.Frame4.configure(width=555)

        self.Message9 = Message(self.Frame4)
        self.Message9.place(relx=0.054, rely=0.027, relheight=0.232
                , relwidth=0.905)
        self.Message9.configure(background="#d9d9d9")
        self.Message9.configure(font=font13)
        self.Message9.configure(foreground="#000000")
        self.Message9.configure(highlightbackground="#d9d9d9")
        self.Message9.configure(highlightcolor="#000000")
        self.Message9.configure(text='''Vector & Matrix Calculator''')
        self.Message9.configure(width=502)

        self.Message10 = Message(self.Frame4)
        self.Message10.place(relx=0.072, rely=0.533, relheight=0.179
                , relwidth=0.85)
        self.Message10.configure(background="#d9d9d9")
        self.Message10.configure(font=font14)
        self.Message10.configure(foreground="#000000")
        self.Message10.configure(highlightbackground="#d9d9d9")
        self.Message10.configure(highlightcolor="black")
        self.Message10.configure(text='''Yeo Chee Ket''')
        self.Message10.configure(width=472)

        self.Message11 = Message(self.Frame4)
        self.Message11.place(relx=0.378, rely=0.693, relheight=0.099
                , relwidth=0.238)
        self.Message11.configure(background="#d9d9d9")
        self.Message11.configure(foreground="#000000")
        self.Message11.configure(highlightbackground="#d9d9d9")
        self.Message11.configure(highlightcolor="black")
        self.Message11.configure(text='''BS17110355''')
        self.Message11.configure(width=132)

        self.Message12 = Message(self.Frame4)
        self.Message12.place(relx=0.414, rely=0.453, relheight=0.099
                , relwidth=0.166)
        self.Message12.configure(background="#d9d9d9")
        self.Message12.configure(foreground="#000000")
        self.Message12.configure(highlightbackground="#d9d9d9")
        self.Message12.configure(highlightcolor="black")
        self.Message12.configure(text='''done by:''')
        self.Message12.configure(width=90)

        self.Frame1 = Frame(self.TNotebook1_t1)
        self.Frame1.place(relx=0.017, rely=0.024, relheight=0.378, relwidth=0.5)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=295)

        self.Message1 = Message(self.Frame1)
        self.Message1.place(relx=0.034, rely=0.323, relheight=0.561
                , relwidth=0.312)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Vector 1:

Vector 2:''')
        self.Message1.configure(width=90)

        self.Message2 = Message(self.Frame1)
        self.Message2.place(relx=0.441, rely=0.065, relheight=0.239
                , relwidth=0.112)
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''X''')
        self.Message2.configure(width=90)

        self.Message3 = Message(self.Frame1)
        self.Message3.place(relx=0.746, rely=0.065, relheight=0.239
                , relwidth=0.108)
        self.Message3.configure(background="#d9d9d9")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(text='''Y''')
        self.Message3.configure(width=90)

        self.Entry1 = Entry(self.Frame1)
        self.Entry1.place(relx=0.373, rely=0.323,height=36, relwidth=0.251)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font10)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=74)

        self.Entry2 = Entry(self.Frame1)
        self.Entry2.place(relx=0.678, rely=0.323,height=36, relwidth=0.251)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font=font10)
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=74)

        self.Entry3 = Entry(self.Frame1)
        self.Entry3.place(relx=0.373, rely=0.645,height=36, relwidth=0.251)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font=font10)
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(width=74)

        self.Entry4 = Entry(self.Frame1)
        self.Entry4.place(relx=0.678, rely=0.645,height=36, relwidth=0.251)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font=font10)
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(width=74)

        self.Labelframe1 = LabelFrame(self.TNotebook1_t1)
        self.Labelframe1.place(relx=0.542, rely=0.0, relheight=0.963
                , relwidth=0.441)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Operations''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(width=260)

        self.Button1 = Button(self.Labelframe1)
        self.Button1.place(relx=0.077, rely=0.101, height=42, width=218
                , bordermode='ignore')
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Addition''')
        self.Button1.configure(width=218)
        self.Button1.configure(command=self.vecAdd)

        self.Button2 = Button(self.Labelframe1)
        self.Button2.place(relx=0.077, rely=0.228, height=42, width=218
                , bordermode='ignore')
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Subtraction''')
        self.Button2.configure(width=218)
        self.Button2.configure(command=self.vecSub)

        self.Button3 = Button(self.Labelframe1)
        self.Button3.place(relx=0.077, rely=0.481, height=42, width=218
                , bordermode='ignore')
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Dot Product''')
        self.Button3.configure(width=218)
        self.Button3.configure(command=self.vecMag)

        self.Button4 = Button(self.Labelframe1)
        self.Button4.place(relx=0.077, rely=0.354, height=42, width=218
                , bordermode='ignore')
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Magnitude''')
        self.Button4.configure(width=218)
        self.Button4.configure(command=self.vecDP)

        self.Button5 = Button(self.Labelframe1)
        self.Button5.place(relx=0.077, rely=0.608, height=42, width=218
                , bordermode='ignore')
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Multiplication (cA)''')
        self.Button5.configure(width=218)
        self.Button5.configure(command=self.vecMult)

        self.Message4 = Message(self.Labelframe1)
        self.Message4.place(relx=0.115, rely=0.785, relheight=0.094
                , relwidth=0.181, bordermode='ignore')
        self.Message4.configure(background="#d9d9d9")
        self.Message4.configure(foreground="#000000")
        self.Message4.configure(highlightbackground="#d9d9d9")
        self.Message4.configure(highlightcolor="black")
        self.Message4.configure(text='''c =''')
        self.Message4.configure(width=90)

        self.Entry5 = Entry(self.Labelframe1)
        self.Entry5.place(relx=0.346, rely=0.785, height=36, relwidth=0.477
                , bordermode='ignore')
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font=font10)
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(width=124)

        self.Frame2 = Frame(self.TNotebook1_t1)
        self.Frame2.place(relx=0.017, rely=0.439, relheight=0.5, relwidth=0.5)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=295)

        self.Message5 = Message(self.Frame2)
        self.Message5.place(relx=0.068, rely=0.244, relheight=0.717
                , relwidth=0.888)
        self.Message5.configure(background="#d9d9d9")
        self.Message5.configure(foreground="#000000")
        self.Message5.configure(highlightbackground="#d9d9d9")
        self.Message5.configure(highlightcolor="black")
        self.Message5.configure(width=262)

        self.Label1 = Label(self.Frame2)
        self.Label1.place(relx=0.034, rely=0.049, height=31, width=78)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Answer:''')
        self.Label1.configure(width=78)

        self.Labelframe2 = LabelFrame(self.TNotebook1_t2)
        self.Labelframe2.place(relx=0.017, rely=0.0, relheight=0.402
                , relwidth=0.458)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Matrix A''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(width=270)

        self.Entry6 = Entry(self.Labelframe2)
        self.Entry6.place(relx=0.074, rely=0.242, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font=font10)
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(width=104)

        self.Entry7 = Entry(self.Labelframe2)
        self.Entry7.place(relx=0.519, rely=0.242, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font=font10)
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(width=104)

        self.Entry8 = Entry(self.Labelframe2)
        self.Entry8.place(relx=0.074, rely=0.606, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font=font10)
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(width=104)

        self.Entry9 = Entry(self.Labelframe2)
        self.Entry9.place(relx=0.519, rely=0.606, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font=font10)
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(width=104)

        self.Labelframe3 = LabelFrame(self.TNotebook1_t2)
        self.Labelframe3.place(relx=0.508, rely=0.0, relheight=0.402
                , relwidth=0.458)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Matrix B''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(width=270)

        self.Entry10 = Entry(self.Labelframe3)
        self.Entry10.place(relx=0.074, rely=0.242, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font=font10)
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(width=104)

        self.Entry11 = Entry(self.Labelframe3)
        self.Entry11.place(relx=0.519, rely=0.242, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font=font10)
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(width=104)

        self.Entry12 = Entry(self.Labelframe3)
        self.Entry12.place(relx=0.074, rely=0.606, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry12.configure(background="white")
        self.Entry12.configure(disabledforeground="#a3a3a3")
        self.Entry12.configure(font=font10)
        self.Entry12.configure(foreground="#000000")
        self.Entry12.configure(insertbackground="black")
        self.Entry12.configure(width=104)

        self.Entry13 = Entry(self.Labelframe3)
        self.Entry13.place(relx=0.519, rely=0.606, height=36, relwidth=0.385
                , bordermode='ignore')
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font=font10)
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(insertbackground="black")
        self.Entry13.configure(width=104)

        self.Labelframe4 = LabelFrame(self.TNotebook1_t2)
        self.Labelframe4.place(relx=0.017, rely=0.415, relheight=0.549
                , relwidth=0.458)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Operations''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(width=270)

        self.Button6 = Button(self.Labelframe4)
        self.Button6.place(relx=0.037, rely=0.178, height=42, width=118
                , bordermode='ignore')
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Addition''')
        self.Button6.configure(width=118)
        self.Button6.configure(command=self.matadd)

        self.Button7 = Button(self.Labelframe4)
        self.Button7.place(relx=0.519, rely=0.178, height=42, width=118
                , bordermode='ignore')
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''Subtraction''')
        self.Button7.configure(width=118)
        self.Button7.configure(command=self.matsub)

        self.Button8 = Button(self.Labelframe4)
        self.Button8.place(relx=0.037, rely=0.4, height=42, width=118
                , bordermode='ignore')
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''Multiplication''')
        self.Button8.configure(width=118)
        self.Button8.configure(command=self.matmult)

        self.Button9 = Button(self.Labelframe4)
        self.Button9.place(relx=0.519, rely=0.4, height=42, width=118
                , bordermode='ignore')
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(text='''Scalar Product''')
        self.Button9.configure(width=118)
        self.Button9.configure(command=self.matscal)

        self.Entry14 = Entry(self.Labelframe4)
        self.Entry14.place(relx=0.519, rely=0.711, height=36, relwidth=0.422
                , bordermode='ignore')
        self.Entry14.configure(background="white")
        self.Entry14.configure(disabledforeground="#a3a3a3")
        self.Entry14.configure(font=font10)
        self.Entry14.configure(foreground="#000000")
        self.Entry14.configure(insertbackground="black")
        self.Entry14.configure(width=114)

        self.Message6 = Message(self.Labelframe4)
        self.Message6.place(relx=0.111, rely=0.711, relheight=0.164
                , relwidth=0.378, bordermode='ignore')
        self.Message6.configure(background="#d9d9d9")
        self.Message6.configure(foreground="#000000")
        self.Message6.configure(highlightbackground="#d9d9d9")
        self.Message6.configure(highlightcolor="black")
        self.Message6.configure(text='''Scalar:''')
        self.Message6.configure(width=102)

        self.Frame3 = Frame(self.TNotebook1_t2)
        self.Frame3.place(relx=0.508, rely=0.439, relheight=0.524
                , relwidth=0.466)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(width=275)

        self.Message7 = Message(self.Frame3)
        self.Message7.place(relx=0.036, rely=0.047, relheight=0.172
                , relwidth=0.305)
        self.Message7.configure(background="#d9d9d9")
        self.Message7.configure(foreground="#000000")
        self.Message7.configure(highlightbackground="#d9d9d9")
        self.Message7.configure(highlightcolor="black")
        self.Message7.configure(text='''Answer:''')
        self.Message7.configure(width=84)

        self.Message8 = Message(self.Frame3)
        self.Message8.place(relx=0.036, rely=0.233, relheight=0.73
                , relwidth=0.916)
        self.Message8.configure(background="#d9d9d9")
        self.Message8.configure(foreground="#000000")
        self.Message8.configure(highlightbackground="#d9d9d9")
        self.Message8.configure(highlightcolor="black")
        self.Message8.configure(width=252)

    def matadd(self):
        self.matA[0][0] = int(self.Entry6.get())
        self.matA[0][1] = int(self.Entry7.get())
        self.matA[1][0] = int(self.Entry8.get())
        self.matA[1][1] = int(self.Entry9.get())
        self.matB[0][0] = int(self.Entry10.get())
        self.matB[0][1] = int(self.Entry11.get())
        self.matB[1][0] = int(self.Entry12.get())
        self.matB[1][1] = int(self.Entry13.get())
        ans = self.matA + self.matB
        self.Message8.configure(text=ans)
        print(ans)

    def matsub(self):
        self.matA[0][0] = int(self.Entry6.get())
        self.matA[0][1] = int(self.Entry7.get())
        self.matA[1][0] = int(self.Entry8.get())
        self.matA[1][1] = int(self.Entry9.get())
        self.matB[0][0] = int(self.Entry10.get())
        self.matB[0][1] = int(self.Entry11.get())
        self.matB[1][0] = int(self.Entry12.get())
        self.matB[1][1] = int(self.Entry13.get())
        ans = self.matA - self.matB
        self.Message8.configure(text=ans)
        print(ans)

    def matmult(self):
        self.matA[0][0] = int(self.Entry6.get())
        self.matA[0][1] = int(self.Entry7.get())
        self.matA[1][0] = int(self.Entry8.get())
        self.matA[1][1] = int(self.Entry9.get())
        self.matB[0][0] = int(self.Entry10.get())
        self.matB[0][1] = int(self.Entry11.get())
        self.matB[1][0] = int(self.Entry12.get())
        self.matB[1][1] = int(self.Entry13.get())
        ans = num.dot(self.matA, self.matB)
        self.Message8.configure(text=ans)
        print(ans)

    def matscal(self):
        if self.Entry14.get() is None:
            self.Message8.configure(text="Error")
        else:
            k = num.array([[int(self.Entry14.get()), 0], [0, int(self.Entry14.get())]])
            self.matA[0][0] = int(self.Entry6.get())
            self.matA[0][1] = int(self.Entry7.get())
            self.matA[1][0] = int(self.Entry8.get())
            self.matA[1][1] = int(self.Entry9.get())
        ans = num.dot(self.matA, k)
        self.Message8.configure(text=ans)
        print(ans)

    def vecAdd(self):
        self.vecA[0] = int(self.Entry1.get())
        self.vecA[1] = int(self.Entry2.get())
        self.vecB[0] = int(self.Entry3.get())
        self.vecB[1] = int(self.Entry4.get())
        ans = self.vecA + self.vecB
        self.Message5.configure(text=ans)
        print(ans)

    def vecSub(self):
        self.vecA[0] = int(self.Entry1.get())
        self.vecA[1] = int(self.Entry2.get())
        self.vecB[0] = int(self.Entry3.get())
        self.vecB[1] = int(self.Entry4.get())
        ans = self.vecA - self.vecB
        self.Message5.configure(text=ans)
        print(ans)

    def vecMag(self):
        self.vecA[0] = int(self.Entry1.get())
        self.vecA[1] = int(self.Entry2.get())
        sq = (self.vecA[0] * self.vecA[0]) + (self.vecA[1] * self.vecA[1])
        ans = math.sqrt(sq)
        self.Message5.configure(text=ans)
        print(ans)

    def vecDP(self):
        self.vecA[0] = int(self.Entry1.get())
        self.vecA[1] = int(self.Entry2.get())
        self.vecB[0] = int(self.Entry3.get())
        self.vecB[1] = int(self.Entry4.get())
        ans = (self.vecA[0]*self.vecB[0])+(self.vecA[1]*self.vecB[1])
        self.Message5.configure(text=ans)
        print(ans)

    def vecMult(self):
        self.vecA[0] = int(self.Entry1.get())
        self.vecA[1] = int(self.Entry2.get())
        y = int(self.Entry5.get())
        ans = [self.vecA[0]*y, self.vecA[1]*y]
        txt = "x = " + str(ans[0]) + ", y = " + str(ans[1])
        print(txt)
        self.Message5.configure(text=txt)




if __name__ == '__main__':
    vp_start_gui()



