#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 15, 2018 07:41:15 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Algerian -size 15 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family Constantia -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 594x450+719+101
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1050
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo40 \
        -width 594 -height 446 -takefocus {} 
    vTcl:DefineAlias "$top.tNo40" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo40.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo40.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo40 add $top.tNo40.t0 \
        -padding 0 -sticky nsew -state normal -text {Main Menu} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo40.t0
    frame $site_4_0.fra85 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 375 \
        -width 555 
    vTcl:DefineAlias "$site_4_0.fra85" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra85
    message $site_5_0.mes86 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font13,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor {#000000} -text {Vector & Matrix Calculator} \
        -width 502 
    vTcl:DefineAlias "$site_5_0.mes86" "Message9" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes88 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font14,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Yeo Chee Ket} -width 472 
    vTcl:DefineAlias "$site_5_0.mes88" "Message10" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes90 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text BS17110355 \
        -width 132 
    vTcl:DefineAlias "$site_5_0.mes90" "Message11" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes91 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {done by:} \
        -width 90 
    vTcl:DefineAlias "$site_5_0.mes91" "Message12" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.mes86 \
        -in $site_5_0 -x 30 -y 10 -width 502 -relwidth 0 -height 87 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.mes88 \
        -in $site_5_0 -x 40 -y 200 -width 472 -relwidth 0 -height 67 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.mes90 \
        -in $site_5_0 -x 210 -y 260 -width 132 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.mes91 \
        -in $site_5_0 -x 230 -y 170 -anchor nw -bordermode ignore 
    place $site_4_0.fra85 \
        -in $site_4_0 -x 20 -y 20 -width 555 -relwidth 0 -height 375 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo40.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo40.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo40 add $top.tNo40.t1 \
        -padding 0 -sticky nsew -state normal -text {Vector Calculator} \
        -image {} -compound left -underline -1 
    set site_4_1  $top.tNo40.t1
    frame $site_4_1.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 155 \
        -width 295 
    vTcl:DefineAlias "$site_4_1.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.fra43
    message $site_5_0.mes44 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Vector 1:

Vector 2:} -width 90 
    vTcl:DefineAlias "$site_5_0.mes44" "Message1" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes45 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text X \
        -width 90 
    vTcl:DefineAlias "$site_5_0.mes45" "Message2" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes46 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Y \
        -width 90 
    vTcl:DefineAlias "$site_5_0.mes46" "Message3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent47 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent47" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent48 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent48" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent50 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent50" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent51 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent51" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.mes44 \
        -in $site_5_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_5_0.mes45 \
        -in $site_5_0 -x 130 -y 10 -anchor nw -bordermode ignore 
    place $site_5_0.mes46 \
        -in $site_5_0 -x 220 -y 10 -anchor nw -bordermode ignore 
    place $site_5_0.ent47 \
        -in $site_5_0 -x 110 -y 50 -width 74 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent48 \
        -in $site_5_0 -x 200 -y 50 -width 74 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent50 \
        -in $site_5_0 -x 110 -y 100 -width 74 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent51 \
        -in $site_5_0 -x 200 -y 100 -width 74 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_1.lab52 \
        -foreground black -text Operations -background {#d9d9d9} -height 395 \
        -width 260 
    vTcl:DefineAlias "$site_4_1.lab52" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.lab52
    button $site_5_0.but54 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Addition 
    vTcl:DefineAlias "$site_5_0.but54" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Subtraction 
    vTcl:DefineAlias "$site_5_0.but55" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Dot Product} 
    vTcl:DefineAlias "$site_5_0.but56" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but57 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Magnitude 
    vTcl:DefineAlias "$site_5_0.but57" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but58 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Multiplication (cA)} 
    vTcl:DefineAlias "$site_5_0.but58" "Button5" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes59 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {c =} \
        -width 90 
    vTcl:DefineAlias "$site_5_0.mes59" "Message4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent60 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent60" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.but54 \
        -in $site_5_0 -x 20 -y 40 -width 218 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but55 \
        -in $site_5_0 -x 20 -y 90 -width 218 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but56 \
        -in $site_5_0 -x 20 -y 190 -width 218 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but57 \
        -in $site_5_0 -x 20 -y 140 -width 218 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but58 \
        -in $site_5_0 -x 20 -y 240 -width 218 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.mes59 \
        -in $site_5_0 -x 30 -y 310 -anchor nw -bordermode ignore 
    place $site_5_0.ent60 \
        -in $site_5_0 -x 90 -y 310 -width 124 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_4_1.fra61 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 205 \
        -width 295 
    vTcl:DefineAlias "$site_4_1.fra61" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.fra61
    message $site_5_0.mes62 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {} \
        -width 262 
    vTcl:DefineAlias "$site_5_0.mes62" "Message5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab63 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Answer: 
    vTcl:DefineAlias "$site_5_0.lab63" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.mes62 \
        -in $site_5_0 -x 20 -y 50 -width 262 -relwidth 0 -height 147 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab63 \
        -in $site_5_0 -x 10 -y 10 -width 78 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra43 \
        -in $site_4_1 -x 10 -y 10 -width 295 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab52 \
        -in $site_4_1 -x 320 -y 0 -width 260 -relwidth 0 -height 395 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra61 \
        -in $site_4_1 -x 10 -y 180 -width 295 -relwidth 0 -height 205 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo40.t2 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo40.t2" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo40 add $top.tNo40.t2 \
        -padding 0 -sticky nsew -state normal -text {Matrix Calculator} \
        -image {} -compound none -underline -1 
    set site_4_2  $top.tNo40.t2
    labelframe $site_4_2.lab64 \
        -foreground black -text {Matrix A} -background {#d9d9d9} -height 165 \
        -width 270 
    vTcl:DefineAlias "$site_4_2.lab64" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_2.lab64
    entry $site_5_0.ent66 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent66" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent67 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent67" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent68 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent68" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent69 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent69" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent66 \
        -in $site_5_0 -x 20 -y 40 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent67 \
        -in $site_5_0 -x 140 -y 40 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent68 \
        -in $site_5_0 -x 20 -y 100 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent69 \
        -in $site_5_0 -x 140 -y 100 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_2.lab65 \
        -foreground black -text {Matrix B} -background {#d9d9d9} -height 165 \
        -width 270 
    vTcl:DefineAlias "$site_4_2.lab65" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_2.lab65
    entry $site_5_0.ent70 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent70" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent71 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent71" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent72 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent72" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent73 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent73" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent70 \
        -in $site_5_0 -x 20 -y 40 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent71 \
        -in $site_5_0 -x 140 -y 40 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent72 \
        -in $site_5_0 -x 20 -y 100 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent73 \
        -in $site_5_0 -x 140 -y 100 -width 104 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_2.lab74 \
        -foreground black -text Operations -background {#d9d9d9} -height 225 \
        -width 270 
    vTcl:DefineAlias "$site_4_2.lab74" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_2.lab74
    button $site_5_0.but75 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Addition 
    vTcl:DefineAlias "$site_5_0.but75" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but76 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Subtraction 
    vTcl:DefineAlias "$site_5_0.but76" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but77 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Multiplication 
    vTcl:DefineAlias "$site_5_0.but77" "Button8" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but78 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Scalar Product} 
    vTcl:DefineAlias "$site_5_0.but78" "Button9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent79 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent79" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes80 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Scalar: \
        -width 102 
    vTcl:DefineAlias "$site_5_0.mes80" "Message6" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.but75 \
        -in $site_5_0 -x 10 -y 40 -width 118 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but76 \
        -in $site_5_0 -x 140 -y 40 -width 118 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but77 \
        -in $site_5_0 -x 10 -y 90 -width 118 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but78 \
        -in $site_5_0 -x 140 -y 90 -width 118 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent79 \
        -in $site_5_0 -x 140 -y 160 -width 114 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.mes80 \
        -in $site_5_0 -x 30 -y 160 -width 102 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_4_2.fra81 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 215 \
        -width 275 
    vTcl:DefineAlias "$site_4_2.fra81" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_2.fra81
    message $site_5_0.mes83 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Answer: \
        -width 84 
    vTcl:DefineAlias "$site_5_0.mes83" "Message7" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes84 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {} \
        -width 252 
    vTcl:DefineAlias "$site_5_0.mes84" "Message8" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.mes83 \
        -in $site_5_0 -x 10 -y 10 -width 84 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.mes84 \
        -in $site_5_0 -x 10 -y 50 -width 252 -relwidth 0 -height 157 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab64 \
        -in $site_4_2 -x 10 -y 0 -width 270 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab65 \
        -in $site_4_2 -x 300 -y 0 -width 270 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab74 \
        -in $site_4_2 -x 10 -y 170 -width 270 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.fra81 \
        -in $site_4_2 -x 300 -y 180 -width 275 -relwidth 0 -height 215 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo40 \
        -in $top -x 0 -y 0 -width 594 -relwidth 0 -height 446 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

